export const Images = {
  mouth: "/Assets2/PNG/icons8-mouth-64.png",
  computer: "/Assets2/PNG/computer.png",
  design: "/Assets2/PNG/design.png",
  marketing: "/Assets2/PNG/web-marketing.png",
  Ahamove: "/Assets2/PNG/Logo-Ahamove.png",
  DownWithAppStore: "/Assets2/PNG/DownWithAppStore.jpg",
  DownWithCHplay: "/Assets2/PNG/DownWithCHplay.jpg",
  bgFooter: "/Assets2/Images/bgFooter.jpg",
  Advertise: "/Assets2/PNG/Advertise.png",
  unilever: "/Assets2/PNG/unilever.png",
  Puma: "/Assets2/PNG/Puma.png",
  bannerFilter: "/Assets2/Images/bannerFilter.jpg",
  banner: "/Assets2/Images/banner.jpg",
  banner1: "/Assets2/Images/banner1.jpg",
  bgRegisterIcon: "/Assets2/PNG/bgRegisterIcon.png",
  logoSlogan: "/Assets2/PNG/LogoSlogan.png",
  bgi: "/Assets2/PNG/NewProject.png",
  check: "/Assets2/PNG/check.png",
  logoApple: "/Assets2/PNG/lgApple.png",
  logoGoogle: "/Assets2/PNG/lgG.png",
  logoFace: "/Assets2/PNG/lgFace.png",
  bannerHome: "/Assets2/PNG/Rectangle65.png",
  banerPreeShip: "/Assets2/PNG/banner2.png",
  banner3: "/Assets2/PNG/Rectangle 66.png",
  banner4: "/Assets2/PNG/Rectangle 620.png",
  car: "/Assets2/PNG/car.png",
  headphones: "/Assets2/PNG/headphones.png",
  shopping: "/Assets2/PNG/shopping-bag.png",
  Group: "/Assets2/PNG/Group.png",
  Category1: "/Assets2/PNG/category1.png",
  Category2: "/Assets2/PNG/category2.png",
  Category3: "/Assets2/PNG/category3.png",
  Category4: "/Assets2/PNG/category4.png",
  Category5: "/Assets2/PNG/category5.png",
  Category6: "/Assets2/PNG/category6.png",
  Category7: "/Assets2/PNG/category7.png",
  Category8: "/Assets2/PNG/category8.png",
  Category9: "/Assets2/PNG/category9.png",
  Category10: "/Assets2/PNG/category10.png",
  Category11: "/Assets2/PNG/category11.png",
  Category12: "/Assets2/PNG/category12.png",
  textMom: "/Assets2/PNG/Group 409.png",
  product: "/Assets2/PNG/product.png",
  imgMom1: "/Assets2/PNG/Rectangle 617.png",
  imgMom2: "/Assets2/PNG/Rectangle 618.png",
  imgMom3: "/Assets2/PNG/Rectangle 619.png",
  star1: "/Assets2/PNG/Star 11.png",
  star2: "/Assets2/PNG/Star 15.png",
  flashSale1: "/Assets2/PNG/flashSale1.png",
  chooseUs1: "/Assets2/PNG/chooseUs1.png",
  chooseUs2: "/Assets2/PNG/chooseUs2.png",
  chooseUs3: "/Assets2/PNG/chooseUsCheck.png",
  chooseUs4: "/Assets2/PNG/chooseUsArrow.png",
  puma: "/Assets2/PNG/puma.png",
  spGoiY1: "/Assets2/PNG/spGoiY1.png",
  thuongHieu2: "/Assets2/PNG/thuongHieu2.png",
  adidas: "/Assets2/PNG/adidas.png",
  thuongHieu1: "/Assets2/PNG/thuongHieu1.png",
  hot: "/Assets2/PNG/hot.png",
  picture: "/Assets2/PNG/picture.png",
  avatar_admin: "../../../src/pages/home/Admin/Assets/Images/avatar.png",
  imageproduct: "../../../src/pages/home/Admin/Assets/Images/imageproduct.png",
  imageproduct1:
    "../../../src/pages/home/Admin/Assets/Images/imageproduct1.png",
  imageproduct2:
    "../../../src/pages/home/Admin/Assets/Images/imageproduct2.png",
  imageproduct3:
    "../../../src/pages/home/Admin/Assets/Images/imageproduct3.png",
  imageproduct4:
    "../../../src/pages/home/Admin/Assets/Images/imageproduct4.png",
  imageproduct5:
    "../../../src/pages/home/Admin/Assets/Images/imageproduct5.png",
  imageproduct6:
    "../../../src/pages/home/Admin/Assets/Images/imageproduct6.png",
  chevron: "../../../src/pages/home/Admin/Assets/Images/chevron-right.png",
  chevron1: "../../../src/pages/home/Admin/Assets/Images/chevron-right1.png",
  Banner: "src/Assets/Images/banner.jpg",
  Banner1: "src/Assets/Images/banner1.jpg",
  BannerQC: "../../../src/pages/home/Admin/Assets/Images/bannerQC.png",
  imgProduct: "../../../src/pages/home/Admin/Assets/Images/imgProduct.jpg",
  cateAD: "/Assets2/PNG/cate.png",
  Avtcmt: "/Assets2/Images/Avtcmt.png",
  momo: "/Assets2/PNG/momo.png",
  zalo: "/Assets2/PNG/Logo-ZaloPay.png",
  nhanHang: "/Assets2/PNG/nhanhang.png",
  detailHover: "/Assets2/PNG/Line 56.png",
  visa: "/Assets2/PNG/294654_visa_icon.png",
  EmptyPage: "/Assets2/PNG/Group 863.png",

  viettelpost: "/Assets2/JPG/VTPost.jpg",
  ghn: "/Assets2/PNG/GHN.png",
  bestex: "/Assets2/PNG/bestex.png",
  GHTK: "/Assets2/PNG/GHTK.png",
  ninjavan: "/Assets2/PNG/ninjavan.png",
  JT: "/Assets2/PNG/J&T.png",
  vnpost: "/Assets2/PNG/vnpost.png",
  momo2: "/Assets2/PNG/momo2.png",
  zalopay: "/Assets2/PNG/zalopay.png",

  emptyPages: "/Assets2/PNG/emptyPage.png",
};
