export const Images = {
  mouth: "../src/Assets/PNG/icons8-mouth-64.png",
  computer: "../src/Assets/PNG/computer.png",
  design: "../src/Assets/PNG/design.png",
  marketing: "../src/Assets/PNG/web-marketing.png",
  Ahamove: "../src/Assets/PNG/Logo-Ahamove.png",
  DownWithAppStore: "../src/Assets/PNG/DownWithAppStore.jpg",
  DownWithCHplay: "../src/Assets/PNG/DownWithCHplay.jpg",
  bgFooter: "../Images/bgFooter.jpg",
  Advertise: "../src/Assets/PNG/Advertise.png",
  unilever: "../src/Assets/PNG/unilever.png",
  Puma: "../src/Assets/PNG/Puma.png",
  bannerFilter: "../src/Assets/Images/bannerFilter.jpg",
  banner: "../src/Assets/Images/banner.jpg",
  banner1: "../src/Assets/Images/banner1.jpg",
  bgRegisterIcon: "../src/Assets/PNG/bgRegisterIcon.png",
  logoSlogan: "../src/Assets/PNG/logoSlogan.png",
  logoApple: "../src/Assets/PNG/lgApple.png",
  logoGoogle: "../src/Assets/PNG/lgG.png",
  logoFace: "../src/Assets/PNG/lgFace.png",
  bannerHome: "../src/Assets/PNG/Rectangle65.png",
  banerPreeShip: "../src/Assets/PNG/banner2.png",
  banner3: "../src/Assets/PNG/Rectangle 66.png",
  banner4: "../src/Assets/PNG/Rectangle 620.png",
  car: "../src/Assets/PNG/car.png",
  headphones: "../src/Assets/PNG/headphones.png",
  shopping: "../src/Assets/PNG/shopping-bag.png",
  Group: "../src/Assets/PNG/Group.png",
  Category1: "../src/Assets/PNG/category1.png",
  Category2: "../src/Assets/PNG/category2.png",
  Category3: "../src/Assets/PNG/category3.png",
  Category4: "../src/Assets/PNG/category4.png",
  Category5: "../src/Assets/PNG/category5.png",
  Category6: "../src/Assets/PNG/category6.png",
  Category7: "../src/Assets/PNG/category7.png",
  Category8: "../src/Assets/PNG/category8.png",
  Category9: "../src/Assets/PNG/category9.png",
  Category10: "../src/Assets/PNG/category10.png",
  Category11: "../src/Assets/PNG/category11.png",
  Category12: "../src/Assets/PNG/category12.png",
  textMom: "../src/Assets/PNG/Group 409.png",
  product: "../src/Assets/PNG/product.png",
  imgMom1: "../src/Assets/PNG/Rectangle 617.png",
  imgMom2: "../src/Assets/PNG/Rectangle 618.png",
  imgMom3: "../src/Assets/PNG/Rectangle 619.png",
  star1: "../src/Assets/PNG/Star 11.png",
  star2: "../src/Assets/PNG/Star 15.png",
  flashSale1: "../src/Assets/PNG/flashSale1.png",
  chooseUs1: "../src/Assets/PNG/chooseUs1.png",
  chooseUs2: "../src/Assets/PNG/chooseUs2.png",
  chooseUs3: "../src/Assets/PNG/chooseUsCheck.png",
  chooseUs4: "../src/Assets/PNG/chooseUsArrow.png",
  puma: "../src/Assets/PNG/puma.png",
  spGoiY1: "../src/Assets/PNG/spGoiY1.png",
  thuongHieu2: "../src/Assets/PNG/thuongHieu2.png",
  adidas: "../src/Assets/PNG/adidas.png",
  thuongHieu1: "../src/Assets/PNG/thuongHieu1.png",
  hot: "../src/Assets/PNG/hot.png",
  picture: "../src/Assets/PNG/picture.png",
  avatar_admin: "../../../src/pages/home/Admin/Assets/Images/avatar.png",
  imageproduct: "../../../src/pages/home/Admin/Assets/Images/imageproduct.png",
  imageproduct1: "../../../src/pages/home/Admin/Assets/Images/imageproduct1.png",
  imageproduct2: "../../../src/pages/home/Admin/Assets/Images/imageproduct2.png",
  imageproduct3: "../../../src/pages/home/Admin/Assets/Images/imageproduct3.png",
  imageproduct4: "../../../src/pages/home/Admin/Assets/Images/imageproduct4.png",
  imageproduct5: "../../../src/pages/home/Admin/Assets/Images/imageproduct5.png",
  imageproduct6: "../../../src/pages/home/Admin/Assets/Images/imageproduct6.png",
  chevron: "../../../src/pages/home/Admin/Assets/Images/chevron-right.png",
  chevron1: "../../../src/pages/home/Admin/Assets/Images/chevron-right1.png",
  Banner: "../src/Assets/Images/banner.jpg",
  Banner1: "../src/Assets/Images/banner1.jpg",
  BannerQC: "../../../src/pages/home/Admin/Assets/Images/bannerQC.png",
  imgProduct: "../../../src/pages/home/Admin/Assets/Images/imgProduct.jpg",
  cateAD: "../src/Assets/PNG/cate.png",
  Avtcmt: "../src/Assets/Images/Avtcmt.png",

};

