export const Images = {
  mouth: "../src/Assets/PNG/icons8-mouth-64.png",
  computer: "../src/Assets/PNG/computer.png",
  design: "../src/Assets/PNG/design.png",
  marketing: "../src/Assets/PNG/web-marketing.png",
  Ahamove: "../src/Assets/PNG/Logo-Ahamove.png",
  DownWithAppStore: "../src/Assets/PNG/DownWithAppStore.jpg",
  DownWithCHplay: "../src/Assets/PNG/DownWithCHplay.jpg",
  bgFooter: "../Images/bgFooter.jpg",
  bgRegisterIcon: "../src/Assets/PNG/bgRegisterIcon.png",
  logoSlogan:"../src/Assets/PNG/logoSlogan.png",
  bannerHome: '../src/Assets/PNG/Rectangle65.png',
  banerPreeShip: '../src/Assets/PNG/banner2.png',
  banner3: '../src/Assets/PNG/Rectangle 66.png',
  banner4: '../src/Assets/PNG/Rectangle 620.png',
  car: '../src/Assets/PNG/car.png',
  headphones: '../src/Assets/PNG/headphones.png',
  shopping: '../src/Assets/PNG/shopping-bag.png',
  Group: '../src/Assets/PNG/Group.png',
  Category1: '../src/Assets/PNG/category1.png',
  Category2: '../src/Assets/PNG/category2.png',
  Category3: '../src/Assets/PNG/category3.png',
  Category4: '../src/Assets/PNG/category4.png',
  Category5: '../src/Assets/PNG/category5.png',
  Category6: '../src/Assets/PNG/category6.png',
  Category7: '../src/Assets/PNG/category7.png',
  Category8: '../src/Assets/PNG/category8.png',
  Category9: '../src/Assets/PNG/category9.png',
  Category10: '../src/Assets/PNG/category10.png',
  Category11: '../src/Assets/PNG/category11.png',
  Category12: '../src/Assets/PNG/category12.png',
  textMom : '../src/Assets/PNG/Group 409.png',
  imgMom1 : '../src/Assets/PNG/Rectangle 617.png',
  imgMom2 : '../src/Assets/PNG/Rectangle 618.png',
  imgMom3 : '../src/Assets/PNG/Rectangle 619.png',
};
